package Calculator;


/**
* Calculator/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Saturday, 3 May, 2025 4:02:56 PM IST
*/

public interface CalcOperations 
{
  int calculate (int type, int a, int b);
  void exit ();
} // interface CalcOperations
